// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY86Ka4VTyqBN0LFOOeFcZ1VQ1V2Z3jOg',
    appId: '1:564687588404:web:0903825b4fdc53729ece61',
    messagingSenderId: '564687588404',
    projectId: 'ailton-dez-app',
    authDomain: 'ailton-dez-app.firebaseapp.com',
    storageBucket: 'ailton-dez-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcqNtwuc-qx4V6cWQDTyxX0yPftsQ8ya0',
    appId: '1:564687588404:android:c6f1be2e89d9ce089ece61',
    messagingSenderId: '564687588404',
    projectId: 'ailton-dez-app',
    storageBucket: 'ailton-dez-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB36gUcNwnNVjcsrfNJ6FZFj810okMmi7w',
    appId: '1:564687588404:ios:67a4cc2fc1db58379ece61',
    messagingSenderId: '564687588404',
    projectId: 'ailton-dez-app',
    storageBucket: 'ailton-dez-app.firebasestorage.app',
    iosBundleId: 'com.example.ailtonDez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB36gUcNwnNVjcsrfNJ6FZFj810okMmi7w',
    appId: '1:564687588404:ios:67a4cc2fc1db58379ece61',
    messagingSenderId: '564687588404',
    projectId: 'ailton-dez-app',
    storageBucket: 'ailton-dez-app.firebasestorage.app',
    iosBundleId: 'com.example.ailtonDez',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY86Ka4VTyqBN0LFOOeFcZ1VQ1V2Z3jOg',
    appId: '1:564687588404:web:238c2b0215fccaef9ece61',
    messagingSenderId: '564687588404',
    projectId: 'ailton-dez-app',
    authDomain: 'ailton-dez-app.firebaseapp.com',
    storageBucket: 'ailton-dez-app.firebasestorage.app',
  );
}
